### ISSUE TITLE
dosbox fatal error

### ISSUE THREAD

**Issue by tehmoth** [rxi/lovedos#1]
$ dosbox ./love.exe  
DOSBox version 0.74
## Copyright 2002-2010 DOSBox Team, published under GNU GPL.

CONFIG: Generating default configuration.
Writing it to /home/jamesw/.dosbox/dosbox-0.74.conf
CONFIG:Loading primary settings from config file ~/.dosbox/dosbox-0.74.conf
MIXER:Got different values from SDL: freq 44100, blocksize 882
MIDI:Opened device:none
Using joystick /dev/uhid0 with 0 axes, 0 buttons and 0 hat(s)
Using joystick /dev/uhid1 with 0 axes, 0 buttons and 0 hat(s)
DOSBox switched to max cycles, because of the setting: cycles=auto. If the game runs too fast try a fixed cycles amount in DOSBox's options.
Exit to error: DRC64:Unhandled memory reference

**Comment by rxi** [comment]
Do you have your `core` set to `dynamic` in your dosbox-0.74.conf file? If so can you try setting it to `normal` and report back?

```
core = normal
```

**Comment by vext01** [comment]
I have the same running the game "A fragile allegiance" on OpenBSD (0.74).

Switching core to normal or simple gives a stack trace for a moment, then crashes hard with a message "hybrid strikes again".

**Comment by denilsonsa** [comment]
This is not an issue with LoveDOS. However, this issue is one of the top results in Google search for that error message.

The actual bug is in the dynamic core from DOSBox:
- https://sourceforge.net/p/dosbox/bugs/413/
- http://www.vogons.org/viewtopic.php?f=32&t=45111

This issue should probably be closed, and people hitting this error message (myself included) should follow that bug or that thread instead of this issue. (or try the latest SVN version of DOSBox)

**Comment by vext01** [comment]
Agreed

**Comment by rxi** [comment]
Thanks @denilsonsa

**Comment by sparkprince** [comment]
<h1>Turbo C++ installation with problem fixing</h1>
Ok, finally **I fixed my problem**.
I was trying to run "*Turbo C++*" in Ubuntu and I was facing problem and then I solved it. Please read it to last..
<h2>Installation</h2>
<br>-Open "*terminal*".<br>

-Type `sudo apt-get install dosbox` to *install Dosbox*.

-When it is installed *download TC*([download this Turbo C++][1]) and *extract it and paste it in home directory*.
<br><br>
![screenshot from 2018-05-04 11-00-09](https://user-images.githubusercontent.com/38851654/39614098-a3291816-4f8a-11e8-9532-a5ce28f4f8c3.png)
<br>

-Type `dosbox` in terminal to open it.

-**Create a configuration file** by typing this command on dosbox console
 

    config -writeconf dosbox.conf


> [Note: *By default dosbox.conf file is created in home directory*.]

- Write these commands on *dosbox console*
<br>`mount c ~`
or
`mount c ~ /home/your_username/`
<br>`c:`
<br>`cd tc/bin`
<br>`tc.exe`or`tc`
<br>
<br>Now, when I tried "tc.exe". It was just getting closed/crash and showing this in the terminal
<br>







 

> DOSBox switched to max cycles, because of the setting: cycles=auto. If
> the game runs too fast try a fixed cycles amount in DOSBox's options.
> 
>Exit to error: DRC64:Unhandled memory reference `

<h3>FIX Problem shown in "Terminal"</h3>

I did this and every thing is working fine:-
<br>1. open "dosbox.conf" present in the your home folder.<br>
<br>
![screenshot from 2018-05-04 11-00-09](https://user-images.githubusercontent.com/38851654/39614098-a3291816-4f8a-11e8-9532-a5ce28f4f8c3.png)
<br>
2. change things like this<br>

    core=normal
    cputype=normal
    cycles=normal
    

<br>

![screenshot from 2018-05-04 10-25-19](https://user-images.githubusercontent.com/38851654/39613532-7fdfd5f2-4f85-11e8-9848-90e8e33a2677.png)
<br>
or if you want you can try "*simple*" instead of "*normal*". But "*normal*" works fine.<br>
This is it **SAVE and Exit** " dosbox.confi" and then start your dosbox again.
<br><br>

<h3>Auto-run turbo C++</h3>

Ok guys, after fixing your problem. Whenever you open DOSBox. **Everytime you have to mount it** and this is grate headache. Fox solving this follow this-
<br>-Open "dosbox.confi"
<br>-Go at the bottom and add this commands for your Turbo C++ auto-run in Dos-box.


<br>`mount c ~ /home/prince`
<br>
<br>`c:`
<br>`cd tc`
<br>`cd bin`
<br>`tc`
<br>
![screenshot from 2018-05-04 11-18-32](https://user-images.githubusercontent.com/38851654/39614420-66a1f28e-4f8d-11e8-9e81-7300a429ee58.png)
<br>
 and **SAVE & Exit** and now run and test it.

<h2>Full-screen problem</h2>    

That is all it was not in **full screen mode**. That is why I changed this thing -
<br>

    fullscreen=true
    fulldouble=false
    fullresolution=your computer resolution
    windowresolution=your computer resolution
    output=overlay
    autolock=false

<br>


![screenshot from 2018-05-04 10-26-30](https://user-images.githubusercontent.com/38851654/39614739-b8b04998-4f8f-11e8-9793-a6ec0e9262d3.png)

<br>
and for finding your computer resolution. Open terminal and type this

    xdpyinfo | grep 'dimensions:'

<br>


![screenshot from 2018-05-04 10-28-36](https://user-images.githubusercontent.com/38851654/39613598-f04e863a-4f85-11e8-86ce-6866d7785d1f.png)

<br>

  [1]: https://mega.nz/#!IBNEjR6Q!29i94B-7-hwPZjPi1jEKFspkDddRiTBrAHNAnOfuRb4
  [2]: https://i.stack.imgur.com/RKOre.png


<br><br><br><br><h1>Please help me increasing my reputation</h1>

**Comment by denilsonsa** [comment]
@sparkprince as much as I can appreciate the effort writing this tutorial, this is the wrong place to put it. Publish it in your blog, your webpage, at some forum, as a GitHub Gist, [or even at askubuntu.com](https://askubuntu.com/help/self-answer). But here, your tutorial is completely unrelated to this project and to this (closed) issue.
